CREATE TABLE "data"."form_data" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "id_fl" 					int4 NOT NULL,
	"id_form" 				int4 NOT NULL,
  "date_create" 		timestamp(6),
	"question_group" 	int4 NOT NULL,
	"question_unit"  	int4,
  "question" 				varchar(500) COLLATE "pg_catalog"."default" NOT NULL,
  "question_answer" varchar(500) COLLATE "pg_catalog"."default",
  "answer_text" 		varchar(500) COLLATE "pg_catalog"."default",
	 
	 CONSTRAINT "form_data_pkey" PRIMARY KEY ("id")
)
;

ALTER TABLE "data"."form_land" 
  OWNER TO "postgres";

COMMENT ON COLUMN "data"."form_data"."id" 							IS 'Идентификатор';

COMMENT ON COLUMN "data"."form_data"."id_fl" 						IS 'Идентификатор строки исходных данных';

COMMENT ON COLUMN "data"."form_data"."id_form" 					IS 'Идентификатор анкеты';

COMMENT ON COLUMN "data"."form_data"."date_create" 			IS 'ДатаВремя ответа на анкету';

COMMENT ON COLUMN "data"."form_data"."question_group" 	IS 'Номер блока вопросов';

COMMENT ON COLUMN "data"."form_data"."question_unit" 		IS 'Номер вопроса в блоке';

COMMENT ON COLUMN "data"."form_data"."question" 				IS 'Вопрос';

COMMENT ON COLUMN "data"."form_data"."question_answer" 	IS 'Вариант ответа';

COMMENT ON COLUMN "data"."form_data"."answer_text" 			IS 'Текст ответа';

